apiVersion: v1
kind: PersistentVolume
metadata:
  name: airbnb-backend-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: airbnb-local-storage
  local:
    path: /var/lib/airbnb-guestbook
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node-1
