apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbnb-backend-data
  namespace: airbnb-welcome
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: airbnb-local-storage
  resources:
    requests:
      storage: 1Gi
